# Project info
site_name: IBM Cloud Satellite L3 for Sales Demonstration
site_description: IBM Cloud Satellite Sales Enablement Level 3 Demonstration
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-Satellite-L3-Sales
#repo_url: https://github.com/IBM/SalesEnablement-Satellite-L3-Sales/
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Home: README.md
  - Part 1 - IBM Cloud Satellite overview and provisioning:
    - 'Introduction': 'environment/01.01 Introduction.md'
    - 'What are IBM Cloud Satellite Locations': 'environment/02.01 What are Locations.md'
    - 'Watch: How to provision a Satellite Location in AWS': 'environment/02.02 Watch: How to provision a Location in AWS.md'
    - 'Next steps': 'environment/05.01 Next steps.md'
  - Part 2 - Deploy an IBM Cloud Satellite enabled service:
    - 'Introduction': 'deploy-sat-enabled-services/01.01 Introduction.md'
    - 'Explore Satellite enabled services': 'deploy-sat-enabled-services/02.01 ExploreSatServices.md'
    - 'Watch: Deploying Red Hat OpenShift to an IBM Cloud Satellite Location': 'deploy-sat-enabled-services/03.01 Watch: Deploy ROKS to Sat.md'
    - 'Next steps': 'deploy-sat-enabled-services/05.01 Next steps.md'
  - Part 3 - Deploy an OpenShift application:
    - 'Introduction and terminology': 'deploy-application/01.01 Introduction.md'
    - 'The Food Delivery Application': 'deploy-application/01.02 The Food Delivery Application.md'
    - 'Demonstration flow': 'deploy-application/01.03 Demonstration flow.md'
    - 'Watch how its done': 'deploy-application/01.04 Watch the demonstration.md'
    - 'View cluster groups': 'deploy-application/02.01 Create cluster groups.md'
    - 'View configuration': 'deploy-application/03.01 Create a configuration.md'
    - 'Create versions using IBM Cloud Portal': 'deploy-application/03.02 Create versions using IBM Cloud Portal.md'
    - 'Create versions using Command Line Interfaces': 'deploy-application/03.02 Create versions using command line interfaces.md'
    - 'Create subscriptions': 'deploy-application/03.03 Create subscriptions.md'
    - 'Verify the application is deployed': 'deploy-application/03.04 Verify the application is deployed.md'
    - 'Update the development and production frontends': 'deploy-application/04.01 Update the development and production frontends.md'
    - 'Perform a rollback': 'deploy-application/04.02 Perform a rollback.md'
    - 'Next steps': 'deploy-application/05.01 Next steps.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - search
    - mkdocs-video:
        is_video: True
        video_autoplay: False
    - macros

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  generator: false
  learningplan:
    name: "IBM Cloud Satellite Sales Level 3"
    url: "https://yourlearning.ibm.com/activity/PLAN-7D757C8B58E7"
  tz_environment:
    name: "IBM Cloud Satellite - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
    uuid_label: "Demo-UUID"
  account: "2435442 - ITZ - Satellite"
  aws:
    location: yl-l3-aws
    host_ip: ip-10-0-1-107
    cluster_name: yl-l3-aws-roks-1
    cluster_id: cadlt2tw0qdi2q6casvg
    ingress: yl-l3-aws-roks-1-222b3514854c2221251113b2b051506c-0000.us-east.containers.appdomain.cloud
  ibm:
    cluster_name: yl-l3-ibm-roks-1
    cluster_id: ca1ttn8w0tjjga091nl0
    ingress: yl-l3-ibm-roks-1-222b3514854c2221251113b2b051506c-0000.us-east.containers.appdomain.cloud
  appdeployment:
    prod_cluster_group: "yl_food_delivery_production"
    dev_cluster_group: "yl_food_delivery_development"
